graph LR
    subgraph "<b>AI Agents</b>"
        direction TB
        Agent1("fa:fa-user-md Claims Agent")
        Agent2("fa:fa-user-nurse Provider Advocate")
        Agent3("fa:fa-hands-helping Member Assist Agent")
    end

    subgraph "<b>MCP Gateway</b>"
        direction TB
        Gateway["<b>Authentication</b>
        <b>Authorization</b>
        <b>Observability</b>
        <b>Tool Scanning</b><br/>IP Restriction"]
    end

    subgraph "<b>MCP Servers</b>"
        direction TB
        Server1["Eligibility<br>MCP Server"]
        Server2["Benefit Check<br>MCP Server"]
        Server3["Claims Inquiry<br>MCP Server"]
        Server4["Payments<br> MCP Server"]
    end

    subgraph "<b>Tools & Resources</b>"
        direction TB
        Tool1["fa:fa-clipboard-list Eligibility Database/API"]
        Tool5["fa:fa-clipboard-list Eligibility API"]
        Tool2["fa:fa-file-invoice-dollar Benefit Plan API"]
        Tool3["fa:fa-handshake Claims History Database"]
        Tool4["fa:fa-credit-card Payments Gateway"]
    end

    %% Connections
    Agent1 -- "Query" --> Gateway
    Agent2 -- "Query" --> Gateway
    Agent3 -- "Query" --> Gateway

    Gateway --> Server1
    Gateway --> Server2
    Gateway --> Server3
    Gateway --> Server4

    Server1 --> Tool1
    Server1 --> Tool5
    Server2 --> Tool2
    Server3 --> Tool3
    Server4 --> Tool4

    %% Styling
    classDef agentStyle fill:#0F2540,color:#fff,stroke-width:0px,rx:8,ry:8,font-weight:bold
    classDef gatewayStyle fill:#e6e6e6,color:#000,stroke-width:2px,stroke:#0F2540,font-weight:bold,rx:8,ry:8
    classDef serverStyle fill:#0F2540,color:#fff,stroke-width:0px,rx:8,ry:8
    classDef toolStyle fill:#e6e6e6,color:#000,stroke-width:0px,rx:8,ry:8

    class Agent1,Agent2,Agent3 agentStyle;
    class Gateway gatewayStyle;
    class Server1,Server2,Server3,Server4 serverStyle;
    class Tool1,Tool2,Tool3,Tool4,Tool5 toolStyle;